
import os
os.environ.setdefault("DJANGO_SETTINGS_MODULE", "saveyourvote.settings")
import string
from voterreg.models import IndianState, IndianDistrict

DISTRICTS = [
    ('08', "Agra"),
    ('09', "Aligarh"),
    ('29', "Allahabad"),
    ('70', "Ambedkar Nagar"),
    ('72', "Amethi"),
    ('22', "Amroha"),
    ('28', "Auraiya"),
    ('47', "Azamgarh"),
    ('07', "Baghpat"),
    ('64', "Baharaich"),
    ('49', "Balia"),
    ('65', "Balrampur"),
    ('38', "Banda"),
    ('69', "Barabanki"),
    ('15', "Bareilly"),
    ('54', "Basti"),
    ('21', "Bijnor"),
    ('16', "Budaun"),
    ('05', "Bulandsahar"),
    ('43', "Chandauli"),
    ('39', "Chitrakoot"),
    ('52', "Deoria"),
    ('13', "Etah"),
    ('25', "Etawah"),
    ('67', "Faizabad"),
    ('26', "Farrukhabad"),
    ('30', "Fatehpur"),
    ('11', "Firozabad"),
    ('06', "Gautam Buddha Nagar"),
    ('04', "Ghaziabad"),
    ('42', "Ghazipur"),
    ('63', "Gonda"),
    ('50', "Gorakhpur"),
    ('36', "Hamirpur"),
    ('73', "Hapur"),
    ('61', "Hardoi"),
    ('14', "Hathras"),
    ('35', "Jalaun"),
    ('41', "Jaunpur"),
    ('33', "Jhansi"),
    ('27', "Kannauj"),
    ('24', "Kanpur Dehat"),
    ('23', "Kanpur Nagar"),
    ('71', "Kasganj"),
    ('32', "Kaushambi"),
    ('62', "Kheri"),
    ('53', "Kushinagar"),
    ('34', "Lalitpur"),
    ('57', "Lucknow"),
    ('51', "Maharajganj"),
    ('37', "Mahoba"),
    ('12', "Manpuri"),
    ('10', "Mathura"),
    ('48', "Mau"),
    ('03', "Meerut"),
    ('44', "Mirzapur"),
    ('19', "Moradabad"),
    ('02', "Muzaffarnagar"),
    ('18', "Pilibhit"),
    ('31', "Pratapgarh"),
    ('59', "Rae Bareli"),
    ('20', "Rampur"),
    ('01', "Saharanpur"),
    ('75', "Sambhal"),
    ('56', "Sant Kabir Nagar"),
    ('46', "Sant Ravidas Nagar"),
    ('17', "Shahjahanpur"),
    ('74', "Shamli"),
    ('66', "Shrawasti"),
    ('55', "Siddharthnagar"),
    ('60', "Sitapur"),
    ('45', "Sonbhadra"),
    ('68', "Sultanpur"),
    ('58', "Unnao"),
    ('40', "Varanasi"),
]

UP = IndianState.objects.get(shortcode='UP')

for number, name in DISTRICTS:
    name = string.capwords(name)
    district = IndianDistrict(state=UP, name=name, number=number)
    district.save()
    print district
